export const DOC_TYPES = {
  id_card:              { label: 'ID Card',              emoji: '🪪', color: '#2563eb' },
  passport:             { label: 'Passport',             emoji: '🛂', color: '#8b5cf6' },
  driver_license:       { label: "Driver's License",    emoji: '🚗', color: '#f97316' },
  birth_certificate:    { label: 'Birth Certificate',    emoji: '📋', color: '#22c55e' },
  marriage_certificate: { label: 'Marriage Certificate', emoji: '💒', color: '#ec4899' },
  divorce_document:     { label: 'Divorce Document',     emoji: '📄', color: '#64748b' },
  tax_form:             { label: 'Tax Form',             emoji: '💰', color: '#facc15' },
  health_insurance:     { label: 'Health Insurance',     emoji: '🏥', color: '#06b6d4' },
  residency_permit:     { label: 'Residency Permit',     emoji: '🏠', color: '#84cc16' },
  vehicle_registration: { label: 'Vehicle Registration', emoji: '🚙', color: '#f97316' },
  criminal_record:      { label: 'Criminal Record',      emoji: '⚖️', color: '#a855f7' },
  property_paper:       { label: 'Property Paper',       emoji: '🏘️', color: '#14b8a6' },
  fine:                 { label: 'Fine',                 emoji: '🚨', color: '#ef4444' },
  other:                { label: 'Other',                emoji: '📁', color: '#64748b' },
};
